apiVersion: batch/v1
kind: Job
metadata:
  name: lecheck-job
spec:
  template:
    spec:
      containers:
      - name: lecheck-job
        image: yash5090/lecheck:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
