apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecheck-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: lecheck
  template:
    metadata:
      labels:
        app: lecheck
    spec:
      containers:
        - name: lecheck
          image: yash5090/lecheck:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
